import { db } from '@/lib/db'

/**
 * Prefixes for each role's userCode.
 * Short, human-readable abbreviations — aligned with the seed data so that
 * codes generated by the seed and codes generated at runtime use the same
 * convention:
 *   ADM = Administrateur
 *   TCH = Teacher (Enseignant) — matches seed "TCH-001"…
 *   ELV = Élève
 *   PAR = Parent
 *   STF = Staff (Personnel) — matches seed "STF-001"…
 *   SUP = Super Admin (not stored on User, but kept for completeness)
 */
export const ROLE_PREFIX: Record<string, string> = {
  admin: 'ADM',
  teacher: 'TCH',
  student: 'ELV',
  parent: 'PAR',
  staff: 'STF',
  super_admin: 'SUP',
}

/**
 * Generates a unique, human-friendly userCode for a user.
 *
 * Format: {PREFIX}-{3-digit number}, e.g. "ELV-001", "ENS-042", "PER-007".
 *
 * The number is sequential per role within an institution. For users without
 * an institution (e.g. super admin), the sequence is global.
 *
 * This function queries the database to find the highest existing number
 * for the given prefix + institution, then returns the next one.
 *
 * @param role      The user's role (student, teacher, parent, staff, admin).
 * @param institutionId  Optional institution scope. When provided, codes are
 *                       sequenced per-institution. When null/undefined, codes
 *                       are sequenced globally (for cross-institution users).
 * @returns A unique userCode string like "ELV-001".
 */
export async function generateUserCode(
  role: string,
  institutionId?: string | null
): Promise<string> {
  const prefix = ROLE_PREFIX[role] || 'USR'

  // Find all existing codes with this prefix to determine the next number.
  // We scope by institution so each school has its own ELV-001, ENS-001, etc.
  const whereClause: Record<string, unknown> = {
    userCode: { startsWith: `${prefix}-` },
  }
  if (institutionId) {
    whereClause.institutionId = institutionId
  } else {
    // Users without an institution (e.g. super admin) get a global sequence.
    whereClause.institutionId = null
  }

  const existingUsers = await db.user.findMany({
    where: whereClause,
    select: { userCode: true },
  })

  // Extract the numeric suffix from each existing code and find the max.
  const numbers = existingUsers
    .map((u) => {
      const m = u.userCode?.match(new RegExp(`^${prefix}-(\\d+)$`))
      return m ? parseInt(m[1], 10) : 0
    })
    .filter((n) => !isNaN(n) && n > 0)

  const nextNum = numbers.length > 0 ? Math.max(...numbers) + 1 : 1

  // Pad to 3 digits (supports up to 999 per role per institution).
  // If we ever exceed 999, the number just grows to 4+ digits naturally.
  return `${prefix}-${String(nextNum).padStart(3, '0')}`
}

/**
 * Validates that a userCode is in the expected format: PREFIX-NNN.
 * Used by the login route to quickly distinguish a userCode from an email
 * or full name, so we only run the (expensive) userCode lookup when the
 * input actually looks like a code.
 */
export function looksLikeUserCode(input: string): boolean {
  return /^(ADM|TCH|ELV|PAR|STF|SUP|USR)-\d+$/i.test(input.trim())
}
