import { db } from '@/lib/db'

/**
 * Prefixes for each role's userCode.
 * Short, human-readable abbreviations — aligned with the seed data so that
 * codes generated by the seed and codes generated at runtime use the same
 * convention:
 *   ADM = Administrateur
 *   TCH = Teacher (Enseignant) — matches seed "TCH-001"…
 *   ELV = Élève
 *   PAR = Parent
 *   STF = Staff (Personnel) — matches seed "STF-001"…
 *   SUP = Super Admin (not stored on User, but kept for completeness)
 */
export const ROLE_PREFIX: Record<string, string> = {
  admin: 'ADM',
  teacher: 'TCH',
  student: 'ELV',
  parent: 'PAR',
  staff: 'STF',
  super_admin: 'SUP',
}

/**
 * Generates a unique, human-friendly userCode for a user.
 *
 * Format: {PREFIX}-{3-digit number}, e.g. "ELV-001", "TCH-042".
 *
 * The number is sequential per role. Previously it was scoped per-institution
 * (each institution had its own ELV-001, TCH-001…), but this caused
 * duplicates across institutions — two institutions each having a "TCH-001"
 * meant a login with "TCH-001" could match the wrong user.
 *
 * Now the code is **globally unique**: we find the highest existing number
 * for the given prefix across ALL institutions, then return the next one.
 *
 * @param role      The user's role (student, teacher, parent, staff, admin).
 * @param institutionId  Optional (kept for backward compatibility, but no
 *                        longer used for scoping — codes are global now).
 * @returns A globally unique userCode string like "ELV-001".
 */
export async function generateUserCode(
  role: string,
  institutionId?: string | null
): Promise<string> {
  const prefix = ROLE_PREFIX[role] || 'USR'

  // Find all existing codes with this prefix across ALL institutions
  // (global uniqueness — not per-institution anymore).
  const existingUsers = await db.user.findMany({
    where: {
      userCode: { startsWith: `${prefix}-` },
    },
    select: { userCode: true },
  })

  // Extract the numeric suffix from each existing code and find the max.
  const numbers = existingUsers
    .map((u) => {
      const m = u.userCode?.match(new RegExp(`^${prefix}-(\\d+)$`))
      return m ? parseInt(m[1], 10) : 0
    })
    .filter((n) => !isNaN(n) && n > 0)

  let nextNum = numbers.length > 0 ? Math.max(...numbers) + 1 : 1

  // Safety: verify the generated code doesn't already exist (handles edge
  // cases where the regex didn't match a manually-set code). Keep incrementing
  // until we find a truly unique code.
  let candidate = `${prefix}-${String(nextNum).padStart(3, '0')}`
  while (existingUsers.some((u) => u.userCode === candidate)) {
    nextNum++
    candidate = `${prefix}-${String(nextNum).padStart(3, '0')}`
  }

  return candidate
}

/**
 * Validates that a userCode is in the expected format: PREFIX-NNN.
 * Used by the login route to quickly distinguish a userCode from an email
 * or full name, so we only run the (expensive) userCode lookup when the
 * input actually looks like a code.
 */
export function looksLikeUserCode(input: string): boolean {
  return /^(ADM|TCH|ELV|PAR|STF|SUP|USR)-\d+$/i.test(input.trim())
}
