#!/usr/bin/env python3
"""Generate a detailed PDF guide for the MASOMO Schedule (Emploi du Temps) module."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, Image
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.lib.colors import HexColor

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
ACCENT       = colors.HexColor('#532ec5')
TEXT_PRIMARY  = colors.HexColor('#1e2022')
TEXT_MUTED    = colors.HexColor('#868b91')
BG_SURFACE   = colors.HexColor('#dce0e4')
BG_PAGE      = colors.HexColor('#f2f3f4')
EMERALD      = colors.HexColor('#059669')
EMERALD_LIGHT = colors.HexColor('#d1fae5')
AMBER        = colors.HexColor('#d97706')
AMBER_LIGHT  = colors.HexColor('#fef3c7')
RED          = colors.HexColor('#dc2626')
RED_LIGHT    = colors.HexColor('#fee2e2')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('NotoSerifSC', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans-Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold')
registerFontFamily('LiberationSans', normal='LiberationSans', bold='LiberationSans-Bold')
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')

# ━━ Document Setup ━━
output_path = '/home/z/my-project/Guide_Emploi_du_Temps_MASOMO.pdf'
doc = SimpleDocTemplate(
    output_path,
    pagesize=A4,
    leftMargin=2.0*cm,
    rightMargin=2.0*cm,
    topMargin=2.0*cm,
    bottomMargin=2.0*cm,
)

page_width = A4[0]
available_width = page_width - 4.0*cm

# ━━ Styles ━━
styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    name='DocTitle', fontName='LiberationSerif', fontSize=28,
    leading=36, alignment=TA_CENTER, textColor=ACCENT,
    spaceAfter=6
)

subtitle_style = ParagraphStyle(
    name='DocSubtitle', fontName='LiberationSerif', fontSize=14,
    leading=20, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceAfter=24
)

h1_style = ParagraphStyle(
    name='H1', fontName='LiberationSerif', fontSize=20,
    leading=28, textColor=ACCENT, spaceBefore=18, spaceAfter=12
)

h2_style = ParagraphStyle(
    name='H2', fontName='LiberationSerif', fontSize=15,
    leading=22, textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8
)

h3_style = ParagraphStyle(
    name='H3', fontName='LiberationSerif', fontSize=12,
    leading=18, textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6
)

body_style = ParagraphStyle(
    name='Body', fontName='LiberationSerif', fontSize=10.5,
    leading=17, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
    spaceAfter=6
)

bullet_style = ParagraphStyle(
    name='Bullet', fontName='LiberationSerif', fontSize=10.5,
    leading=17, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=24, bulletIndent=12, spaceAfter=4
)

step_style = ParagraphStyle(
    name='Step', fontName='LiberationSerif', fontSize=10.5,
    leading=17, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=30, spaceAfter=4
)

note_style = ParagraphStyle(
    name='Note', fontName='LiberationSerif', fontSize=10,
    leading=16, alignment=TA_LEFT, textColor=AMBER,
    leftIndent=12, borderPadding=6, spaceAfter=8
)

tip_style = ParagraphStyle(
    name='Tip', fontName='LiberationSerif', fontSize=10,
    leading=16, alignment=TA_LEFT, textColor=EMERALD,
    leftIndent=12, borderPadding=6, spaceAfter=8
)

caption_style = ParagraphStyle(
    name='Caption', fontName='LiberationSerif', fontSize=9,
    leading=14, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceBefore=3, spaceAfter=12
)

header_cell_style = ParagraphStyle(
    name='HeaderCell', fontName='LiberationSerif', fontSize=10,
    leading=14, alignment=TA_CENTER, textColor=colors.white
)

cell_style = ParagraphStyle(
    name='Cell', fontName='LiberationSerif', fontSize=10,
    leading=14, alignment=TA_CENTER, textColor=TEXT_PRIMARY
)

cell_left_style = ParagraphStyle(
    name='CellLeft', fontName='LiberationSerif', fontSize=10,
    leading=14, alignment=TA_LEFT, textColor=TEXT_PRIMARY
)

# ━━ Story ━━
story = []

# ── Title Page ──
story.append(Spacer(1, 80))
story.append(Paragraph('<b>Guide Utilisateur</b>', title_style))
story.append(Spacer(1, 12))
story.append(Paragraph('<b>Emploi du Temps</b>', ParagraphStyle(
    name='Title2', fontName='LiberationSerif', fontSize=22,
    leading=30, alignment=TA_CENTER, textColor=EMERALD
)))
story.append(Spacer(1, 20))
story.append(Paragraph('Application MASOMO - Gestion Scolaire', subtitle_style))
story.append(Spacer(1, 30))

# Separator line
sep_data = [['']]
sep_table = Table(sep_data, colWidths=[available_width * 0.6])
sep_table.setStyle(TableStyle([
    ('LINEABOVE', (0, 0), (-1, 0), 2, ACCENT),
    ('TOPPADDING', (0, 0), (-1, -1), 0),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
]))
story.append(sep_table)

story.append(Spacer(1, 30))
story.append(Paragraph('Ce document explique en detail le fonctionnement du module', body_style))
story.append(Paragraph('Emploi du Temps dans MASOMO et comment le remplir correctement.', body_style))
story.append(Spacer(1, 20))
story.append(Paragraph('Version 1.0 - Mars 2025', ParagraphStyle(
    name='Version', fontName='LiberationSerif', fontSize=11,
    leading=16, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(PageBreak())

# ── Table of Contents ──
story.append(Paragraph('<b>Table des Matieres</b>', h1_style))
story.append(Spacer(1, 12))

toc_items = [
    ('1.', 'Presentation du Module Emploi du Temps'),
    ('2.', 'Acces au Module'),
    ('3.', 'Vue d\'ensemble de l\'interface'),
    ('4.', 'Selection d\'une Classe'),
    ('5.', 'Affichage sur Ordinateur (Grille Hebdomadaire)'),
    ('6.', 'Affichage sur Mobile (Vue par Jour)'),
    ('7.', 'Ajouter un CreneauHoraire'),
    ('8.', 'Supprimer un CreneauHoraire'),
    ('9.', 'Code Couleur par Matiere'),
    ('10.', 'Champs du Formulaire - Detail Complet'),
    ('11.', 'Bonnes Pratiques et Conseils'),
    ('12.', 'Limites Actuelles'),
]

for num, title in toc_items:
    story.append(Paragraph(
        f'<b>{num}</b>  {title}',
        ParagraphStyle(name=f'TOC_{num}', fontName='LiberationSerif', fontSize=11,
                       leading=20, leftIndent=20, textColor=TEXT_PRIMARY)
    ))

story.append(PageBreak())

# ── Section 1: Presentation ──
story.append(Paragraph('<b>1. Presentation du Module Emploi du Temps</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Le module <b>Emploi du Temps</b> permet de planifier les cours hebdomadaires de chaque classe. "
    "Il offre une vue graphique en grille (sur ordinateur) ou par jour (sur mobile) pour visualiser "
    "et gerer facilement les creneaux horaires de chaque classe.",
    body_style
))
story.append(Spacer(1, 8))
story.append(Paragraph("Fonctionnalites principales :", body_style))
story.append(Paragraph("Visualisation de l'emploi du temps par classe sous forme de grille hebdomadaire", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Ajout de creneaux horaires (matiere, enseignant, salle, horaire)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Suppression de creneaux existants", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Code couleur automatique par matiere", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Affichage responsive (ordinateur et mobile)", bullet_style, bulletText='\xe2\x80\xa2'))

# ── Section 2: Acces ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>2. Acces au Module</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "L'emploi du temps est accessible depuis la barre de navigation laterale (menu de gauche) "
    "en cliquant sur <b>Emploi du temps</b>. L'icone represente un livre ouvert.",
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "<b>Remarque :</b> Les administrateurs et les enseignants peuvent ajouter et supprimer des creneaux. "
    "Les eleves et les parents ont un acces en lecture seule.",
    note_style
))

# ── Section 3: Vue d'ensemble ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>3. Vue d\'ensemble de l\'interface</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "L'interface se compose des elements suivants :",
    body_style
))
story.append(Spacer(1, 6))

# Interface overview table
interface_data = [
    [Paragraph('<b>Element</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('En-tete', cell_style), Paragraph('Titre "Emploi du temps" avec sous-titre "Planification hebdomadaire des cours"', cell_left_style)],
    [Paragraph('Selecteur de classe', cell_style), Paragraph('Menu deroulant pour choisir la classe dont on veut voir l\'emploi du temps', cell_left_style)],
    [Paragraph('Bouton Ajouter', cell_style), Paragraph('Bouton vert "Ajouter" pour creer un nouveau creneau (admin/enseignant uniquement)', cell_left_style)],
    [Paragraph('Grille / Liste', cell_style), Paragraph('Zone principale affichant les creneaux sous forme de grille (ordinateur) ou de liste (mobile)', cell_left_style)],
]

interface_table = Table(interface_data, colWidths=[available_width*0.25, available_width*0.70])
interface_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(interface_table)
story.append(Paragraph('Tableau 1 : Elements de l\'interface', caption_style))

# ── Section 4: Selection de classe ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>4. Selection d\'une Classe</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "En haut de la page, un menu deroulant vous permet de selectionner la classe dont vous souhaitez "
    "consulter l'emploi du temps. La premiere classe de la liste est automatiquement selectionnee "
    "au chargement de la page.",
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph("Etapes pour changer de classe :", body_style))
story.append(Paragraph("1. Cliquez sur le menu deroulant en haut a droite de l'en-tete", step_style))
story.append(Paragraph("2. Selectionnez la classe souhaitee dans la liste", step_style))
story.append(Paragraph("3. L'emploi du temps se met a jour automatiquement", step_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Si aucune classe n'est selectionnee, un message vous invite a en choisir une.",
    body_style
))

# ── Section 5: Affichage ordinateur ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>5. Affichage sur Ordinateur (Grille Hebdomadaire)</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Sur ordinateur, l'emploi du temps s'affiche sous forme de grille hebdomadaire avec :",
    body_style
))
story.append(Spacer(1, 6))

# Grid structure table
grid_data = [
    [Paragraph('<b>Colonne</b>', header_cell_style), Paragraph('<b>Contenu</b>', header_cell_style)],
    [Paragraph('Premiere colonne', cell_style), Paragraph('Plages horaires de 08h00 a 17h00 (par tranche d\'1 heure)', cell_left_style)],
    [Paragraph('Colonne Lundi', cell_style), Paragraph('Creneaux du lundi', cell_left_style)],
    [Paragraph('Colonne Mardi', cell_style), Paragraph('Creneaux du mardi', cell_left_style)],
    [Paragraph('Colonne Mercredi', cell_style), Paragraph('Creneaux du mercredi', cell_left_style)],
    [Paragraph('Colonne Jeudi', cell_style), Paragraph('Creneaux du jeudi', cell_left_style)],
    [Paragraph('Colonne Vendredi', cell_style), Paragraph('Creneaux du vendredi', cell_left_style)],
]

grid_table = Table(grid_data, colWidths=[available_width*0.30, available_width*0.65])
grid_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 6), (-1, 6), TABLE_ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(grid_table)
story.append(Paragraph('Tableau 2 : Structure de la grille hebdomadaire', caption_style))

story.append(Paragraph('<b>Creneau occupe :</b>', body_style))
story.append(Paragraph(
    "Lorsqu'un creneau est occupe, une carte coloree s'affiche contenant :",
    body_style
))
story.append(Paragraph("Le nom de la matiere (en gras)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Le nom de l'enseignant (si assigne)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("La salle (si renseignee)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("La plage horaire (ex : 08h00 - 10h00)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Si un cours dure plus d'une heure (ex : 08h00 - 10h00), la carte s'etend sur "
    "plusieurs lignes de la grille pour bien montrer la duree.",
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Cellule vide :</b>', body_style))
story.append(Paragraph(
    "Les cellules vides affichent un bouton \"+\" discret qui apparait au survol. "
    "Cliquer sur ce bouton ouvre le formulaire d'ajout avec le jour et l'heure "
    "pre-remplis pour cette cellule. Ce bouton n'est visible que pour les administrateurs "
    "et les enseignants.",
    body_style
))

# ── Section 6: Affichage mobile ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>6. Affichage sur Mobile (Vue par Jour)</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Sur mobile, l'affichage adapte automatiquement en vue par jour avec :",
    body_style
))
story.append(Paragraph("Barre d'onglets : 5 onglets (Lun, Mar, Mer, Jeu, Ven) pour naviguer entre les jours", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Fleches de navigation : fleches gauche/droite avec le nom du jour entre les deux", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Liste verticale de cartes pour chaque cours du jour selectionne", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Chaque carte de cours affiche le nom de la matiere, l'enseignant, la plage horaire "
    "et la salle. Si aucun cours n'est prevu pour le jour, un message "
    "\"Aucun cours prevu ce jour\" s'affiche.",
    body_style
))

# ── Section 7: Ajouter un creneau ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>7. Ajouter un Creneau Horaire</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>7.1 Ouverture du formulaire</b>', h2_style))
story.append(Paragraph(
    "Il existe deux manieres d'ouvrir le formulaire d'ajout :",
    body_style
))
story.append(Paragraph(
    "<b>Methode 1 :</b> Cliquer sur le bouton vert \"Ajouter\" en haut de la page. "
    "Le formulaire s'ouvre avec la classe actuellement selectionnee pre-remplie.",
    step_style
))
story.append(Paragraph(
    "<b>Methode 2 :</b> Sur la grille (ordinateur), survoler une cellule vide et cliquer "
    "sur le bouton \"+\" qui apparait. Le formulaire s'ouvre avec le jour et l'heure "
    "de la cellule pre-remplis.",
    step_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>7.2 Remplissage du formulaire</b>', h2_style))
story.append(Paragraph(
    "Le formulaire \"Ajouter un creneau\" contient les champs suivants :",
    body_style
))
story.append(Spacer(1, 6))

# Form fields detail table
form_data = [
    [Paragraph('<b>Champ</b>', header_cell_style), Paragraph('<b>Obligatoire</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style), Paragraph('<b>Exemple</b>', header_cell_style)],
    [Paragraph('Classe', cell_style), Paragraph('Oui', cell_style), Paragraph('Menu deroulant listant toutes les classes', cell_left_style), Paragraph('6eme A', cell_style)],
    [Paragraph('Matiere', cell_style), Paragraph('Oui', cell_style), Paragraph('Champ texte libre pour le nom de la matiere', cell_left_style), Paragraph('Mathematiques', cell_style)],
    [Paragraph('Enseignant', cell_style), Paragraph('Non', cell_style), Paragraph('Menu deroulant des enseignants disponibles', cell_left_style), Paragraph('M. Keita', cell_style)],
    [Paragraph('Jour', cell_style), Paragraph('Oui', cell_style), Paragraph('Lundi a Vendredi (menu deroulant)', cell_left_style), Paragraph('Lundi', cell_style)],
    [Paragraph('Heure debut', cell_style), Paragraph('Oui', cell_style), Paragraph('Menu deroulant (07h00 a 17h30, par tranche de 30 min)', cell_left_style), Paragraph('08:00', cell_style)],
    [Paragraph('Heure fin', cell_style), Paragraph('Oui', cell_style), Paragraph('Menu deroulant (filtre apres heure debut)', cell_left_style), Paragraph('10:00', cell_style)],
    [Paragraph('Salle', cell_style), Paragraph('Non', cell_style), Paragraph('Champ texte libre pour la salle', cell_left_style), Paragraph('Salle 201', cell_style)],
]

form_table = Table(form_data, colWidths=[available_width*0.15, available_width*0.13, available_width*0.47, available_width*0.20])
form_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 6), (-1, 6), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 7), (-1, 7), TABLE_ROW_EVEN),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
]))
story.append(form_table)
story.append(Paragraph('Tableau 3 : Champs du formulaire d\'ajout de creneau', caption_style))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>7.3 Etapes detaillees pour ajouter un creneau</b>', h2_style))
story.append(Paragraph("1. Cliquez sur le bouton vert \"Ajouter\" ou sur le \"+\" d'une cellule vide", step_style))
story.append(Paragraph("2. Verifiez que la bonne classe est selectionnee dans le menu deroulant", step_style))
story.append(Paragraph("3. Saisissez le nom de la matiere (ex : \"Mathematiques\", \"Francais\", \"SVT\")", step_style))
story.append(Paragraph("4. (Optionnel) Selectionnez un enseignant dans la liste deroulante", step_style))
story.append(Paragraph("5. Selectionnez le jour de la semaine", step_style))
story.append(Paragraph("6. Choisissez l'heure de debut", step_style))
story.append(Paragraph("7. Choisissez l'heure de fin (doit etre apres l'heure de debut)", step_style))
story.append(Paragraph("8. (Optionnel) Saisissez la salle", step_style))
story.append(Paragraph("9. Cliquez sur le bouton \"Ajouter\"", step_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Un message de confirmation \"Le creneau a ete ajoute a l'emploi du temps\" s'affiche "
    "et la grille se met a jour automatiquement.",
    tip_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>7.4 Validation du formulaire</b>', h2_style))
story.append(Paragraph(
    "Le systeme effectue les verifications suivantes avant l'enregistrement :",
    body_style
))
story.append(Paragraph("Tous les champs obligatoires doivent etre remplis", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("L'heure de fin doit etre strictement apres l'heure de debut", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Les menus deroulant d'heures se filtrent automatiquement (les heures de debut avant l'heure de fin et inversement)", bullet_style, bulletText='\xe2\x80\xa2'))

# ── Section 8: Supprimer ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>8. Supprimer un Creneau Horaire</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Pour supprimer un creneau existant :",
    body_style
))
story.append(Paragraph("1. Sur la grille (ordinateur), cliquez sur la carte du creneau a supprimer", step_style))
story.append(Paragraph("2. Le creneau est immediatement supprime et la grille se met a jour", step_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "<b>Attention :</b> La suppression est immediate, sans confirmation. "
    "Si vous supprimez un creneau par erreur, vous devrez le re-creer manuellement. "
    "Cette action est disponible uniquement pour les administrateurs et les enseignants.",
    note_style
))

# ── Section 9: Code couleur ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>9. Code Couleur par Matiere</b>', h1_style))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Le systeme attribue automatiquement une couleur a chaque matiere de maniere deterministe. "
    "Cela signifie que la meme matiere aura toujours la meme couleur, quel que soit l'emploi "
    "du temps ou la classe affichee.",
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Les 10 couleurs disponibles sont reparties parmi les palettes suivantes : emeraude, turquoise, "
    "cyan, vert, citron vert, ambre, orange, rose, violet. La couleur est attribuee en fonction "
    "du nom de la matiere, garantissant une coherence visuelle.",
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Exemple : \"Mathematiques\" aura toujours la meme couleur, \"Francais\" aura une couleur "
    "differente mais toujours identique d'un affichage a l'autre.",
    tip_style
))

# ── Section 10: Champs detail ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>10. Champs du Formulaire - Detail Complet</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>10.1 Classe (obligatoire)</b>', h2_style))
story.append(Paragraph(
    "Menu deroulant affichant toutes les classes enregistrees dans le systeme. "
    "Par defaut, la classe actuellement selectionnee dans l'emploi du temps est pre-selectionnee. "
    "Vous pouvez changer de classe dans le formulaire si necessaire.",
    body_style
))

story.append(Paragraph('<b>10.2 Matiere (obligatoire)</b>', h2_style))
story.append(Paragraph(
    "Champ texte libre dans lequel vous saisissez le nom de la matiere. "
    "Exemples : Mathematiques, Francais, Anglais, Histoire-Geographie, SVT, EPS, Physique-Chimie. "
    "Le nom saisi determinera la couleur du creneau dans la grille.",
    body_style
))

story.append(Paragraph('<b>10.3 Enseignant (optionnel)</b>', h2_style))
story.append(Paragraph(
    "Menu deroulant listant tous les enseignants enregistres. Le format affiche est : "
    "\"Prenom Nom (Matiere)\". Si un enseignant est selectionne, son nom apparait "
    "dans la carte du creneau. Si aucun enseignant n'est assigne, seule la matiere s'affiche.",
    body_style
))

story.append(Paragraph('<b>10.4 Jour (obligatoire)</b>', h2_style))
story.append(Paragraph(
    "Menu deroulant avec les 5 jours de la semaine :",
    body_style
))

days_data = [
    [Paragraph('<b>Valeur</b>', header_cell_style), Paragraph('<b>Jour</b>', header_cell_style)],
    [Paragraph('1', cell_style), Paragraph('Lundi', cell_style)],
    [Paragraph('2', cell_style), Paragraph('Mardi', cell_style)],
    [Paragraph('3', cell_style), Paragraph('Mercredi', cell_style)],
    [Paragraph('4', cell_style), Paragraph('Jeudi', cell_style)],
    [Paragraph('5', cell_style), Paragraph('Vendredi', cell_style)],
]

days_table = Table(days_data, colWidths=[available_width*0.20, available_width*0.50])
days_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), TABLE_ROW_EVEN),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
]))
story.append(days_table)
story.append(Paragraph('Tableau 4 : Jours de la semaine', caption_style))

story.append(Paragraph(
    "Les samedi et dimanche ne sont pas inclus dans l'emploi du temps.",
    note_style
))

story.append(Paragraph('<b>10.5 Heure de debut et Heure de fin (obligatoires)</b>', h2_style))
story.append(Paragraph(
    "Deux menus deroulants avec des creneaux de 30 minutes, de 07h00 a 17h30 :",
    body_style
))
story.append(Spacer(1, 4))

time_data = [
    [Paragraph('<b>07:00</b>', cell_style), Paragraph('<b>07:30</b>', cell_style), Paragraph('<b>08:00</b>', cell_style), Paragraph('<b>08:30</b>', cell_style), Paragraph('<b>09:00</b>', cell_style)],
    [Paragraph('09:30', cell_style), Paragraph('10:00', cell_style), Paragraph('10:30', cell_style), Paragraph('11:00', cell_style), Paragraph('11:30', cell_style)],
    [Paragraph('12:00', cell_style), Paragraph('12:30', cell_style), Paragraph('13:00', cell_style), Paragraph('13:30', cell_style), Paragraph('14:00', cell_style)],
    [Paragraph('14:30', cell_style), Paragraph('15:00', cell_style), Paragraph('15:30', cell_style), Paragraph('16:00', cell_style), Paragraph('16:30', cell_style)],
    [Paragraph('17:00', cell_style), Paragraph('17:30', cell_style), Paragraph('', cell_style), Paragraph('', cell_style), Paragraph('', cell_style)],
]

time_table = Table(time_data, colWidths=[available_width/5]*5)
time_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), EMERALD_LIGHT),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
]))
story.append(time_table)
story.append(Paragraph('Tableau 5 : Plages horaires disponibles', caption_style))

story.append(Paragraph(
    "Les menus se filtrent automatiquement : l'heure de debut ne propose que les horaires "
    "anterieurs a l'heure de fin selectionnee, et inversement.",
    body_style
))

story.append(Paragraph('<b>10.6 Salle (optionnelle)</b>', h2_style))
story.append(Paragraph(
    "Champ texte libre pour indiquer la salle ou se deroule le cours. "
    "Exemples : \"Salle 201\", \"Laboratoire\", \"Gymnase\", \"CDI\". "
    "Si la salle est renseignee, elle apparait dans la carte du creneau avec une icone de localisation.",
    body_style
))

# ── Section 11: Bonnes pratiques ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>11. Bonnes Pratiques et Conseils</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>11.1 Planification des cours</b>', h2_style))
story.append(Paragraph("Saisissez d'abord les matieres a gros volume horaire (ex : Maths, Francais) avant les matieres secondaires", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Reservez les tranches de 2 heures pour les matieres principales", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Prevoyez des pauses entre les cours intenses (pas 4h de maths d'affilee)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Placez les matieres sportives (EPS) en fin de journee si possible", bullet_style, bulletText='\xe2\x80\xa2'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>11.2 Gestion des enseignants</b>', h2_style))
story.append(Paragraph("Verifiez qu'un enseignant n'est pas assigne a deux classes en meme temps (le systeme ne detecte pas les conflits automatiquement)", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Assignez un enseignant a chaque creneau pour un suivi plus precis", bullet_style, bulletText='\xe2\x80\xa2'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>11.3 Nom des matieres</b>', h2_style))
story.append(Paragraph("Utilisez toujours le meme nom pour une meme matiere (\"Mathematiques\" et non \"Maths\" ou \"Math\")", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Cela garantit que la couleur reste coherente dans tout l'emploi du temps", bullet_style, bulletText='\xe2\x80\xa2'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>11.4 Saisie rapide</b>', h2_style))
story.append(Paragraph("Utilisez le bouton \"+\" sur les cellules vides pour pre-remplir le jour et l'heure", bullet_style, bulletText='\xe2\x80\xa2'))
story.append(Paragraph("Commencez par une classe, remplissez son emploi du temps, puis passez a la suivante", bullet_style, bulletText='\xe2\x80\xa2'))

# ── Section 12: Limites ──
story.append(Spacer(1, 12))
story.append(Paragraph('<b>12. Limites Actuelles</b>', h1_style))
story.append(Spacer(1, 6))

limits_data = [
    [Paragraph('<b>Limite</b>', header_cell_style), Paragraph('<b>Detail</b>', header_cell_style)],
    [Paragraph('Pas de modification', cell_style), Paragraph('Il n\'est pas possible de modifier un creneau existant. Pour le modifier, il faut le supprimer puis le re-creer.', cell_left_style)],
    [Paragraph('Pas de detection de conflits', cell_style), Paragraph('Le systeme ne detecte pas les chevauchements horaires ni les doubles-reservations d\'enseignants.', cell_left_style)],
    [Paragraph('Pas de confirmation de suppression', cell_style), Paragraph('La suppression d\'un creneau est immediate sans dialogue de confirmation.', cell_left_style)],
    [Paragraph('Semaine du lundi au vendredi uniquement', cell_style), Paragraph('Les samedi et dimanche ne sont pas pris en charge.', cell_left_style)],
    [Paragraph('Pas de copie entre classes', cell_style), Paragraph('Il n\'est pas possible de copier l\'emploi du temps d\'une classe a une autre.', cell_left_style)],
    [Paragraph('Pas de glisser-deposer', cell_style), Paragraph('Il n\'est pas possible de deplacer un creneau par glisser-deposer.', cell_left_style)],
]

limits_table = Table(limits_data, colWidths=[available_width*0.30, available_width*0.65])
limits_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 5), (-1, 5), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 6), (-1, 6), TABLE_ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(limits_table)
story.append(Paragraph('Tableau 6 : Limites actuelles du module', caption_style))

story.append(Spacer(1, 24))
story.append(Paragraph(
    "--- Fin du Guide ---",
    ParagraphStyle(name='End', fontName='LiberationSerif', fontSize=11,
                   leading=16, alignment=TA_CENTER, textColor=TEXT_MUTED)
))

# ━━ Build PDF ━━
doc.build(story)
print(f"PDF genere avec succes : {output_path}")
