#!/usr/bin/env bash
# Build a complete source-code ZIP (with database) in public/ folder.
# Downloadable via static URL: http://localhost:3000/MASOMO_Complet.zip

PROJECT_ROOT="/home/z/my-project"
OUTPUT_ZIP="${PROJECT_ROOT}/public/MASOMO_Complet.zip"
STAGE_LIST="${PROJECT_ROOT}/.source-zip-filelist.txt"
ENV_TMP="${PROJECT_ROOT}/.env.tmp.forzip"

cd "$PROJECT_ROOT"

echo "=== Building complete source + database ZIP ==="

# 1. Write corrected .env (RELATIVE path — works on any machine)
cat > "$ENV_TMP" << 'EOF'
# Base de données SQLite (chemin RELATIF — fonctionne sur n'importe quelle machine)
DATABASE_URL="file:./db/custom.db"

# Port de développement
PORT=3000
EOF

# 2. Build file list (everything to include)
{
  # Top-level config + docs
  for f in \
    package.json bun.lock package-lock.json \
    tsconfig.json next.config.ts \
    tailwind.config.ts postcss.config.mjs \
    eslint.config.mjs components.json \
    next-env.d.ts Caddyfile prisma.config.ts .gitignore \
    README.md README-SOURCE.md SETUP.md INSTALLATION-VSCODE.md \
    SOURCE-README.md CHANGELOG.md BUILD_INFO.md \
    NATIVE-BUILD.md BUILD-NATIVE-APPS.md ; do
    [ -f "$f" ] && echo "$f"
  done

  # GitHub Actions workflows (for building native apps on all platforms)
  find .github -type f 2>/dev/null || true

  # Source code
  find src -type f 2>/dev/null || true

  # Prisma (schema + seeds + avatars, NO db binaries)
  find prisma -type f 2>/dev/null | grep -vE '\.(db|db-shm|db-wal)$' || true

  # Mini services + examples + scripts (exclude node_modules to keep the ZIP lean)
  find mini-services -type f 2>/dev/null | grep -vE 'node_modules/' || true
  find examples -type f 2>/dev/null || true
  find scripts -type f 2>/dev/null || true
  find scripts-doc -type f 2>/dev/null || true

  # THE DATABASE
  echo "db/custom.db"
  [ -f "db/export_custom.sql" ] && echo "db/export_custom.sql"

  # Public assets (exclude existing zips, screenshots, heavy files)
  find public -type f 2>/dev/null \
    | grep -vE '\.zip$' \
    | grep -vE 'public/custom\.db$' \
    | grep -vE 'public/(announcements|tool-results|uploads)/' \
    | grep -vE 'public/.*\.(mp4|docx)$' \
    | grep -vE 'public/(dashboard-|login-|payments-|bulletin-|classes-|attendance-|calendar-|comm|parent-|teacher|students-|super-|badge-|restored-|restore-|screenshot|verify-|debug-|step[0-9]|view_|final_|initial-|date-picker|school-year|notifications-|settings-|grades-|homework-|proclamation-|polytech-|lycee-|edugest-|MASOMO)' \
    | grep -vE 'public/.*\.png$' \
    || true

  # Re-include app icons (old flat layout + new public/icons/ folder)
  for icon in \
    public/apple-touch-icon.png \
    public/favicon-16x16.png public/favicon-32x32.png \
    public/icon-72x72.png public/icon-96x96.png \
    public/icon-128x128.png public/icon-144x144.png public/icon-152x152.png \
    public/icon-192x192.png public/icon-384x384.png \
    public/icon-512x512.png \
    public/favicon.ico ; do
    [ -f "$icon" ] && echo "$icon"
  done

  # New PWA icons folder (generated by scripts/generate-icons.mjs)
  find public/icons -type f 2>/dev/null || true

  # ---- Native app wrapper configs ----
  # Tauri (desktop: Windows/macOS/Linux installers)
  find src-tauri -type f 2>/dev/null || true
  # Capacitor (mobile: Android/iOS)
  [ -f capacitor.config.ts ] && echo "capacitor.config.ts"
  # Native build guide
  [ -f NATIVE-BUILD.md ] && echo "NATIVE-BUILD.md"
} | sort -u > "$STAGE_LIST"

COUNT=$(wc -l < "$STAGE_LIST")
echo "Files to zip: $COUNT"

# 3. Build the ZIP (all files except the temp .env)
rm -f "$OUTPUT_ZIP"
grep -v "^${ENV_TMP}$" "$STAGE_LIST" | zip -q -X "$OUTPUT_ZIP" -@

# 4. Add the corrected .env at archive root (renamed from temp)
# Create a temp dir with the .env file properly named
TMPDIR_ENV="$(mktemp -d)"
cp "$ENV_TMP" "${TMPDIR_ENV}/.env"
( cd "$TMPDIR_ENV" && zip -q -X "$OUTPUT_ZIP" ".env" )
rm -rf "$TMPDIR_ENV"

# 5. Cleanup
rm -f "$STAGE_LIST" "$ENV_TMP"

# 6. Report
SIZE=$(du -h "$OUTPUT_ZIP" | cut -f1)
echo ""
echo "============================================"
echo "ZIP created: $OUTPUT_ZIP"
echo "Size:        $SIZE"
echo "Files:       $COUNT"
echo "URL:         http://localhost:3000/MASOMO_Complet.zip"
echo "============================================"
echo ""
echo "=== Database + .env in archive ==="
unzip -l "$OUTPUT_ZIP" | grep -E "custom\.db|^.*\.env$|export_custom" || true
echo ""
echo "=== Total archive entries ==="
unzip -l "$OUTPUT_ZIP" | tail -3
